### ISSUE TITLE
Hello Docker

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1108]
Build a simple program that does the following and can be reused
- [x] Ask for and number of docker containers
- [x] Start a base CentOS image with sshd installed
- [x] Write a `pool.json` that can be consumed by frameworks that will currently utilize ansible

Testkit only
- [x] Dockerize
- [x] Run functional tests using the testkit docker container targeting the provisioned docker cluster

**Comment by tleyden** [comment]
@seth you might consider just prototyping "by hand" -- eg trivial bash script to start the containers, and then trying to run ansible against them.

Choosing the write docker image might be tricky, since you'll need sshd and systemd ..

You might check out https://hub.docker.com/r/alvaroaleman/centos7-systemd-sshd/, which has a dockerfile in github: https://github.com/alvaroaleman/docker-centos7-systemd-sshd/blob/master/Dockerfile

If that doesn't work you might want to roll your own and use that Dockerfile as a starting point

**Comment by sethrosetter** [comment]
@tleyden Sounds like a plan!
