### ISSUE TITLE
Performance scenario: Write throughput

### ISSUE THREAD

**Issue by adamcfraser** [couchbaselabs/mobile-testkit#607]
Common question is what's the max write throughtput I can get for Sync Gateway running on a given machine spec
Also covers the commonly reported issue: memory keeps increasing as I write docs

Parameters:
- # writers
- # channels
- total # docs
- doc size
- bulk docs size (each write has to authenicate, so slow)
- number of goroutines per writer (lower priority)

Test Steps:
- write until done
- monitor CPU and memory usage
- report how long it takes for writes to complete

Action items:

- [ ] Enhance sg simulator to return more realistic responses
- [x] Add something that can push statds
- [ ] Channel names -- should be suffix uuids for no interference between tests
- [ ] Reproduce [issue 1934 scenario](https://github.com/couchbase/sync_gateway/issues/1934#issuecomment-232283822)

**Comment by sethrosetter** [comment]
@adamcfraser For 'report how long it takes for writes to complete', is monitoring response time for the doc POST sufficient? Would PUT / POST for docs make a difference as well? Currently we are just running `POST /db/`

**Comment by sethrosetter** [comment]
- [ ] Still need aggregate stat collection at the end.

**Comment by tleyden** [comment]
- Write a million docs
- Batches of 1k
- Do we need to create 1k users?

Ans: single writer issuing parallel requests

**Comment by tleyden** [comment]
* Doc body -- should have multiple fields, for testing sync function

**Comment by tleyden** [comment]
I've implemented the following in [sgload](https://github.com/couchbaselabs/sgload):

* Added a `--batchsize` parameter -- if greater than 1, will use the `_bulk_docs` endpoint to create documents
* Created [sgsimulator](https://github.com/couchbaselabs/sgload/blob/master/sgsimulator/sgsimulator.go#L55-L81) which is a "no-op" SG that receives the requests and sends *mostly empty responses.  The point is to differentiate between latency introduced by the load generator client and the network op overhead and the Sync Gateway backpressure.

* **mostly empty responses** -- note: I just realized I need to update it to send more realistic responses, since they can have some slight network overhead

With the following cluster on EC2:

* SG instance m3.medium with [sg config](https://gist.github.com/tleyden/f6ce85d251455ded8d64a71c1feb0289#file-testfest-sync-gateway-config-json-L7-L12) 
* CBS instance m3.medium  
* LoadGenerator instance m3.medium

and the following params used in all cases:

| Param        | Val           |
| ------------- | ------------- | 
| createusers      | true |
| numwriters      | 100      |
| numdocs  | 10000      |    
| numchannels | 10      |     

the results were:

| sg target        |  batchsize  | total time |
| ------------- |  ----- | ----- |
| normal sg      |  1 | 1m47.350s |
| normal sg |   50 | 1m40.839s |
| sg simulator      |    1 | 2.857s |
| sg simulator |    50 | 1.020s |

Observations:

* The sg simulator felt effective in establishing the client + network hop latency
* The batch size of 50 had much less of a perf improvement on Sync Gateway than it did on the sg simulator
* The couchbase server ops hovered around 600 ops/sec, peaked out at 800 ops/sec
* I'd be curious to distinguish the "create user" time with the "actual write" time -- one way we could do that is to:
    1. Run with the `--createusers` param, but have sgload return the list of users as json after the run
    1. In the next run, specify `--usercreds` and pass the json from the first run with the existing user creds, so it would skip the user creation step

sgload commands:

```
time sgload writeload --batchsize 1 --createusers --numwriters 100 --numdocs 10000 --numchannels 10 --sg-admin-port 4985 --sg-url "http://ec2-54-237-220-190.compute-1.amazonaws.com:4984/sgload/"
time sgload writeload --batchsize 50 --createusers --numwriters 100 --numdocs 10000 --numchannels 10 --sg-admin-port 4985 --sg-url "http://ec2-54-237-220-190.compute-1.amazonaws.com:4984/sgload/"
time sgload writeload --batchsize 1 --createusers --numwriters 100 --numdocs 10000 --numchannels 10 --sg-admin-port 8000 --sg-url "http://ec2-54-237-220-190.compute-1.amazonaws.com:8000/sgload/"
time sgload writeload --batchsize 50 --createusers --numwriters 100 --numdocs 10000 --numchannels 10 --sg-admin-port 8000 --sg-url "http://ec2-54-237-220-190.compute-1.amazonaws.com:8000/sgload/"
```

**Comment by adamcfraser** [comment]
Some initial thoughts:
 - I assume the sg simulator is running on the SG node?  So it simulates the network overhead between the client and SG, but not the SG-CBS network overhead?
 - I think the scenario runner probably needs to have the concept of 'setup' and 'teardown', where timing isn't calculated.  I don't think it makes sense to be thinking about multiple runs to get the results we need - better to invest that time in integrating that support into the scenario runner.
 - At minimum the scenario runner needs the ability to gather it's own stats and publish them.  In this case, that would be things like:
    - timing for the entire write section of the run
    - stats for individual operation times (average, P95, P99, etc) 
 - Results for running the test against the admin port would be an interesting data point, to remove time spent doing authentication

**Comment by tleyden** [comment]
> I assume the sg simulator is running on the SG node? 

Yep, forgot to mention that

> So it simulates the network overhead between the client and SG, but not the SG-CBS network overhead?

Yeah, I'm treating SG as a "black box" and ignoring it's backhaul.  I meant that the network overhead between the load tool and SG is roughly the same as between the load tool and the sg simulator (aside from the fact the simulator is currently returning smaller responses)

> I think the scenario runner probably needs to have the concept of 'setup' and 'teardown', where timing isn't calculated

Good call, adding that to the action items at the top of this ticket

> At minimum the scenario runner needs the ability to gather it's own stats and publish them

Yeah agreed.  For now I'll update it to add the "timing for the entire write section of the run", and then we can discuss the individual operation times.  

> Results for running the test against the admin port would be an interesting data point, to remove time spent doing authentication

Yeah it shaved off some time:

| sg target        |  batchsize  | total time |
| ------------- |  ----- | ----- |
| su user port      |  1 | 1m47.350s |
| sg user port |   50 | 1m40.839s |
| sg simulator      |    1 | 2.857s |
| sg simulator |    50 | 1.020s |
| **su admin port**      |  1 | 1m20.160s |
| **sg admin port** |   50 | 1m18.143s |

**Comment by tleyden** [comment]
Analytics module:

key value pairs ..

average value for an event type

* Outputs json file
* 

```
{
"document_write_ms":{
  "avg":1.5,
  "max":2.0,
  "min":1.0,
  "p95":1.6,
  "count":5000,
  "total":2000.3,
  "ops_per_second": (count / total),
} 
}
```

**Comment by tleyden** [comment]
* Channel names -- should be uuids for no interference between tests

**Comment by tleyden** [comment]
With https://github.com/couchbaselabs/sgload/commit/b44b3a70d6d924e9d9fba0ab3782be60783d6bce it now pushes statsd stats to influx / grafana.

**Comment by tleyden** [comment]
Usage example

```
sgload writeload --statsdenabled --statsdendpoint http://ip-of-stats-collector:8125
```
