### ISSUE TITLE
Add grafana panel to show active_changes_feed expvar

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/mobile-testkit#752]
Existing sg expvar for showing number of active changes feed.  Should add this to perf test grafana panel

**Comment by ajres** [comment]
New panel has been added to the internal grafana dashboard.

The dashboard has been exported and pushed to the testkit repo.

**Comment by adamcfraser** [comment]
Looked at this dashboard panel for this test run:
http://s61103cnt72.sc.couchbase.com:3000/dashboard/db/sync-gateway-perf-test?var-perftestrundbs=jenkins-sync-gateway-perf-test-112&from=1479716465696&to=1479723665696

I didn't anticipate the spiked pattern - is that a result of sgload using longpoll instead of continuous replication?
