### ISSUE TITLE
Increase Grafana datasource limit

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#892]
We need to bump this - https://github.com/grafana/grafana/pull/6008/files#diff-c040ed482f548e202df475d0449b66db

Options
- Recompile or update to 4.0-Beta

**Comment by ajres** [comment]
I added the following section to the /etc/grafana/grafana.ini file on the shared grafana host and restarted the grafana service.

This property `org_data_source = 1000` should allow us to have 1000 data sources visible in the UI.

```
#################################### Usage Quotas ##########################
[quota]
enabled = true

#### set quotas to -1 to make unlimited. ####
# limit number of users per Org.
org_user = 100

# limit number of dashboards per Org.
org_dashboard = 100

# limit number of data_sources per Org.
org_data_source = 1000

# limit number of api_keys per Org.
org_api_key = 10

# limit number of orgs a user can create.
user_org = 10

# Global limit of users.
global_user = -1

# global limit of orgs.
global_org = -1

# global limit of dashboards
global_dashboard = -1

# global limit of api_keys
global_api_key = -1

# global limit on number of logged in users.
global_session = -1

```
I have not validated that this setting change as I didn't want to pollute the perf test results with lots of dummy runs. There are currently 46 data sources defined, when we get to 100, then we should validate that the 101th data source appears in the UI.

The long term fix for this issue is to upgrade grafana to 4.0, which is currently in Beta.

**Comment by ajres** [comment]
Grafana on the shared host has been upgraded to 4.1.1

I have logged in and reviewed the dashboard with a couple of test runs, the graphs are appearing in the panels as expected.

@sethrosetter @tleyden please review graph data to make sure there are no changes to the way data is being rendered.
